spring:
  ai:
    openai:
      base-url: https://dashscope.aliyuncs.com/compatible-mode
      api-key: ${API_KEY}
      chat:
        options:
          model: qwen-plus
    mcp:
      client:
        toolcallback:
          enabled: true
        name: mcp-client-sse
        #        stdio:
        #          servers-configuration: classpath:mcp-servers.json
        sse:
          connections:
            server1:
              url: http://localhost:8081
  # 使用web模式的sse主要看自动配置类是否生效SseHttpClientTransportAutoConfiguration
  autoconfigure:
    exclude: org.springframework.ai.autoconfigure.mcp.client.SseWebFluxTransportAutoConfiguration
server:
  port: 8082